development:
  secret_key_base: f0bb10404ff61bc84b50764b3f844df6b6893981f751488a6161d7700e6bf57c3cbe0950dd5a9af83473b1c365cafb657f46a5b822978b53f1ccd20e3873e36e

test:
  secret_key_base: f0bb10404ff61bc84b50764b3f844df6b6893981f751488a6161d7700e6bf57c3cbe0950dd5a9af83473b1c365cafb657f46a5b822978b53f1ccd20e3873e36e
